import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`bg-white ${geistSans.variable} ${geistMono.variable} font-sans`}>
        <header className="bg-white border-b border-gray-100 shadow-sm sticky top-0 z-10">
          <nav className="container mx-auto px-4 py-4 flex justify-between items-center">
            <div className="flex space-x-8">
              <Link href="/" className="text-lg font-medium text-gray-500 hover:text-indigo-600 transition-all duration-300 ease-in-out transform hover:scale-110">
                Inicio
              </Link>
              <Link href="/resources" className="text-lg font-medium text-gray-500 hover:text-indigo-600 transition-all duration-300 ease-in-out transform hover:scale-110">
                Recursos
              </Link>
              <Link href="/analysis" className="text-lg font-medium text-gray-500 hover:text-indigo-600 transition-all duration-300 ease-in-out transform hover:scale-110">
                Analizador 
              </Link>
            </div>
            <Link href="/news" className="text-lg font-medium text-gray-500 hover:text-indigo-600 transition-all duration-300 ease-in-out transform hover:scale-110">
              Noticias
            </Link>
            
          </nav>
        </header>
        <main className="mt-4">
          {children}
        </main>
      </body>
    </html>
  );
}